

# This file was *autogenerated* from the file generator.sage
from sage.all_cmdline import *   # import sage library

_sage_const_9 = Integer(9); _sage_const_10 = Integer(10); _sage_const_2 = Integer(2); _sage_const_6 = Integer(6)
class Generator(BaseGenerator):
    def data(self):
        x = var('x')
        a = randrange(-_sage_const_9 ,_sage_const_10 )
        b = randrange(-_sage_const_9 ,_sage_const_10 )
        p = randrange(_sage_const_2 ,_sage_const_6 )

        return {
            "sum": (a*x**p).add(b*x**p,hold=True),
            "result": (a+b)*x**p,
        }

